---
title: "Analyze lightning model"
author: Thorsten Simon
date: May 2019
output: html_document
---

```{r setup}
library("bamlss")
load("full_model.rda")
ls()
vars <- c("d2m", "q_prof_PC1", "cswc_prof_PC4", "t_prof_PC1", "v_prof_PC2",
          "sqrt_cape", "sqrt_lsp")
d_eval <- subset(d_eval, select = c("counts", vars, "mu", "theta"))
b <- bamlss:::light_bamlss(b)
```

```{r plot-stabsel, fig.width = 7, fig.height = 11, out.width = "100%"}
plot(sel, 25)
```

```{r plot-boost-summary, out.width = "100%"}
boost.plot(b, "loglik.contrib")
```

```{r plot-mu-effects, fig.width = 10, fig.height = 15, out.width = "100%"}
plot(b, model = "mu", scale = 0)
```

```{r plot-theta-effects, out.width = "100%"}
plot(b, model = "theta", scale = 0)
```

```{r plot-trace, fig.width = 10, fig.height = 15, out.width = "100%"}
plot(b, model = "mu", term = "sqrt_cape", which = "samples",
     parameter = TRUE)
```

```{r plot-rooto, out.width = "100%"}
y <- d_eval$counts
par <- subset(d_eval, select = c("mu", "theta"))
obsrvd <- table(y)[1:50]
expect <- sapply(1:50, function(j) sum(fam$d(j, par)))
names(expect) <- 1:50
expect <- as.table(expect)
countreg::rootogram(obsrvd, expect)
```

```{r plot-case, out.width = "100%"}
library("sf")
d_case <- readRDS("case.rds")
fit <- predict(b, newdata = d_case, type = "parameter")
d_case$P10 <- 1 - fam$p(9, fit)

pal <- function(n) {
  colorspace::sequential_hcl(n, "Inferno", rev = TRUE)
}

get_gadm <- function(iso) {
  readRDS(url(sprintf("https://biogeo.ucdavis.edu/data/gadm3.6/Rsf/gadm36_%s_0_sf.rds", iso)))
}

iso3 <- c("AUT", "CHE", "CZE", "DEU", "HRV", "ITA", "SVN")

gadm <- lapply(iso3, get_gadm)
gadm <- do.call(rbind, gadm)

st_crs(gadm) <- st_crs(d_case)
gadm_countries <- st_intersection(st_union(d_case), gadm)

plot(d_case["P10"], pal = pal, nbreaks = 100)
plot(st_geometry(gadm_countries), border = "white", add = TRUE)

```

```{r gg, out.width = "100%"}
library("ggplot2")
library("colorspace")
ggplot() +
  geom_sf(aes(fill = P10), data = d_case) +
  scale_fill_continuous_sequential("Inferno", rev = TRUE) +
  theme_minimal() +
  geom_sf(data = gadm_countries, col = "white", fill = NA)
```

```{r dynmap, out.width = "100%", eval = TRUE}
library("mapview")
mapview(d_case["P10"], col.regions = pal)
```

```{r case2, out.width = "100%"}
d_case <- readRDS("case_2001-09.rds")
times <- as.POSIXct(c(
  "2001-09-15 08:00:00 UTC",
  "2001-09-15 19:00:00 UTC",
  "2001-09-16 01:00:00 UTC",
  "2001-09-16 15:00:00 UTC"
))

d_case <- subset(d_case, time %in% times)
d_case <- subset(d_case, select = c("time", vars))
rownames(d_case) <- NULL

fit <- predict(b, newdata = d_case, type = "parameter")
d_case$P10 <- 1 - fam$p(9, fit)
# label_fun <- as_labeller(function(x) sprintf("2001-09-16 %s UTC", x))

ggplot() + geom_sf(aes(fill = P10), data = d_case) +
  scale_fill_continuous_sequential("Inferno", rev = TRUE) +
  geom_sf(data = gadm_countries, col = "white", fill = NA) +
  facet_wrap(~time, nrow = 1) + theme_minimal() +
  theme(legend.position = "bottom")
```

```{r save_workspace}
save(b, fam, sel, d_eval, d_case, gadm_countries, file = "application.rda")
```



