# Project: BayesX
# Hybrid GNU/BSD makefile for R package 'bayesxsrc'
#
# calls are passed to the "inner makefile". but first
# "${R_HOME}/etc${R_ARCH}/Makeconf" is included which does not work with the
# usual include statement sicne ${R_HOME} may contain spaces.
#

INNERMAKEFILE=dev-Makefile.inner.win

all:
	$(MAKE) -f "${R_HOME}/etc${R_ARCH}/Makeconf" -f $(INNERMAKEFILE) all

BayesX:
	$(MAKE) -f "${R_HOME}/etc${R_ARCH}/Makeconf" -f $(INNERMAKEFILE) BayesX

clean:
	$(MAKE) -f "${R_HOME}/etc${R_ARCH}/Makeconf" -f $(INNERMAKEFILE) clean

.PHONY: all clean BayesX
