gibbsObject <- function(object,...)
	{
	cat("The following objects are returned by gibbs():\n")
	cat("-------------------------------------------------------------------\n")
	cat("call:         The initial function call\n")
	cat("formula:      The model formula\n")
	cat("tf:           A terms object generated from the model formula\n")
	cat("vars:         The single model terms with response\n")
	cat("terms:        The single model terms\n")
	cat("N:            The total number of observations\n")
	cat("keepers:      Number of stored draws during sampling\n")
	cat("K:            Number of smooth terms\n")
	cat("L:            Number of linear terms\n")
	cat("R:            Number of ra() terms\n")
	cat("M:            Number of mu() terms\n")
	cat("fout:         list() of fitted term objects of the gibbs() model\n")
	cat("coefficients: list() of fitted coefficients of the gibbs() model\n")
	cat("residuals:    estimated residuals from the gibbs() model\n")
	cat("response:     The response variable vector\n")
	cat("fitted:       The fitted values of the gibbs() model predictor\n")
	cat("DIC:          The deviance information criterion with estimated number of parameters\n")
	cat("iterations:   The number of iterations of the gibbs() sampler\n")
	cat("burnin:       The burnin period\n")
	cat("thinning:     The thinning parameter\n")
	return(invisible(NULL))
	}